version: "3"
services:
  db:
    extends:
      file: docker/database.yml
      service: db
    networks:
      - bcloud-network
    ports:
      - 3306:3306

  adminer:
    extends:
      file: docker/database.yml
      service: adminer
    networks:
      - bcloud-network
    ports:
      - 8001:9200
  cron:
    extends:
      file: docker/addons.yml
      service: cron
    networks:
      - bcloud-network
  lilypond:
    extends:
      file: docker/addons.yml
      service: lilypond
    networks:
      - bcloud-network
    ports:
      - 3100:8080
  bible-matcher:
    extends:
      file: docker/addons.yml
      service: bible-matcher
    networks:
      - bcloud-network
    ports:
      - 3200:3000

  # elastic:
  #   extends:
  #     file: docker/elastic.yml
  #     service: elasticsearch
  #   restart: always
  #   networks:
  #     - bcloud-network
  #   ports:
  #     - 9200:9200

networks:
  bcloud-network:
