version: "3"
services:
  web:
    extends:
      file: docker/server.yml
      service: web
    restart: always
    depends_on:
      - db
    networks:
      - bcloud-network-staging

  nginx:
    extends:
      file: docker/server.yml
      service: nginx
    restart: always
    links:
      - web
    networks:
      - bcloud-network-staging
    ports:
      - 8001:80

  db:
    extends:
      file: docker/database.yml
      service: db
    restart: always
    networks:
      - bcloud-network-staging

  adminer:
    extends:
      file: docker/database.yml
      service: adminer
    restart: always
    networks:
      - bcloud-network-staging
    ports:
      - 8201:8080

  elastic:
    extends:
      file: docker/elastic.yml
      service: elasticsearch
    restart: always
    networks:
      - bcloud-network-staging

  cron:
    extends:
      file: docker/addons.yml
      service: cron
    restart: always
    networks:
      - bcloud-network-staging

  lilypond:
    extends:
      file: docker/addons.yml
      service: lilypond
    restart: always
    networks:
      - bcloud-network-staging

  bible-matcher:
    extends:
      file: docker/addons.yml
      service: bible-matcher
    restart: always
    networks:
      - bcloud-network-staging

networks:
  bcloud-network-staging:
