version: "3"
services:
  web:
    extends:
      file: docker/server.yml
      service: web
    restart: always
    depends_on:
      - db
    networks:
      - bcloud-network

  nginx:
    extends:
      file: docker/server.yml
      service: nginx
    restart: always
    links:
      - web
    networks:
      - bcloud-network
    ports:
      - 8000:80
      - 443:443

  db:
    extends:
      file: docker/database.yml
      service: db
    restart: always
    networks:
      - bcloud-network

  adminer:
    extends:
      file: docker/database.yml
      service: adminer
    restart: always
    networks:
      - bcloud-network
    ports:
      - 8200:8080

  redis:
    image: "redis:alpine"
    volumes:
      - "productionredis:/data"
    networks:
      - bcloud-network

  elastic:
    extends:
      file: docker/elastic.yml
      service: elasticsearch
    restart: always
    networks:
      - bcloud-network

  lilypond:
    extends:
      file: docker/addons.yml
      service: lilypond
    restart: always
    networks:
      - bcloud-network

  bible-matcher:
    extends:
      file: docker/addons.yml
      service: bible-matcher
    restart: always
    networks:
      - bcloud-network

networks:
  bcloud-network:

volumes:
  productionredis:
    driver: local
