# For more information: https://laravel.com/docs/sail
version: "3"
services:
    laravel.test:
        build:
            context: docker/7.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: sail-7.4/app
        ports:
            - "${APP_PORT:-80}:80"
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
        volumes:
            - ".:/var/www/html"
        networks:
            - sail
        depends_on:
            - db

    db:
        extends:
            file: docker/database.yml
            service: db
        networks:
            - sail
        ports:
            - 3306:3306

    adminer:
        extends:
            file: docker/database.yml
            service: adminer
        networks:
            - sail
        ports:
            - 8001:8080
    cron:
        extends:
            file: docker/addons.yml
            service: cron
        networks:
            - sail
    lilypond:
        extends:
            file: docker/addons.yml
            service: lilypond
        networks:
            - sail
        ports:
            - 3100:8080
    bible-matcher:
        extends:
            file: docker/addons.yml
            service: bible-matcher
        networks:
            - sail
        ports:
            - 3200:3000

    redis:
        image: "redis:alpine"
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - "sailredis:/data"
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
    # mysql:
    #     image: "mysql:8.0"
    #     ports:
    #         - "${FORWARD_DB_PORT:-3306}:3306"
    #     environment:
    #         MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    #         MYSQL_DATABASE: "${DB_DATABASE}"
    #         MYSQL_USER: "${DB_USERNAME}"
    #         MYSQL_PASSWORD: "${DB_PASSWORD}"
    #         MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    #     volumes:
    #         - "sailmysql:/var/lib/mysql"
    #     networks:
    #         - sail
    #     healthcheck:
    #         test: ["CMD", "mysqladmin", "ping"]
networks:
    sail:
        driver: bridge
volumes:
    sailredis:
        driver: local
