version: "3"
services:
  serv:
    extends:
      file: docker/server.yml
      service: web-devel
    networks:
      - bcloud-network
    ports:
      - 8000:8000

  db:
    extends:
      file: docker/database.yml
      service: db
    networks:
      - bcloud-network
    ports:
      - 3306:3306

  php-queue:
    extends:
      file: docker/addons.yml
      service: php-queue
    networks:
      - bcloud-network
    depends_on:
      - db
      - serv

  adminer:
    extends:
      file: docker/database.yml
      service: adminer
    networks:
      - bcloud-network
    ports:
      - 8001:8080
  cron:
    extends:
      file: docker/addons.yml
      service: cron
    networks:
      - bcloud-network
  lilypond:
    extends:
      file: docker/addons.yml
      service: lilypond
    networks:
      - bcloud-network
    ports:
      - 3100:8080
  bible-matcher:
    extends:
      file: docker/addons.yml
      service: bible-matcher
    networks:
      - bcloud-network
    ports:
      - 3200:3000

  # elastic:
  #   extends:
  #     file: docker/elastic.yml
  #     service: elasticsearch
  #   restart: always
  #   networks:
  #     - bcloud-network
  #   ports:
  #     - 9200:9200

networks:
  bcloud-network:
