# For more information: https://laravel.com/docs/sail
version: "3"
services:
    # this needs to be named `laravel.test` because of sail commands
    laravel.test:
        extends:
            file: docker/server.yml
            service: web.local
        networks:
            - sail
        depends_on:
            - db
        ports:
            - "${APP_PORT:-80}:80"

    db:
        extends:
            file: docker/database.yml
            service: db
        networks:
            - sail
        ports:
            - 3306:3306

    adminer:
        extends:
            file: docker/database.yml
            service: adminer
        networks:
            - sail
        ports:
            - 8001:8080

    lilypond:
        extends:
            file: docker/addons.yml
            service: lilypond
        networks:
            - sail
        ports:
            - 3100:8080
    bible-matcher:
        extends:
            file: docker/addons.yml
            service: bible-matcher
        networks:
            - sail
        ports:
            - 3200:3000

    redis:
        image: "redis:alpine"
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - "sailredis:/data"
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]

networks:
    sail:
        driver: bridge
volumes:
    sailredis:
        driver: local
