version: '3'
services:
    elasticsearch:
        build:
            context: ./docker/setup/elastic
            dockerfile: Dockerfile
        environment:
            - http.host=0.0.0.0
            - transport.host=127.0.0.1
            - xpack.security.enabled=false
        volumes:
            - ./data/elastic:/etc/elasticsearch/data
            - ./config/elastic/elasticsearch.yml:/var/zpevnik/elasticsearch/elasticsearch.yml
        ports:
            - '9200:9200'
        networks:
            - bcloud-network

    kibana:
        image: docker.elastic.co/kibana/kibana:7.2.0
        ports:
            - '9010:5601'
        networks:
            - bcloud-network
        depends_on:
            - elasticsearch

    # cerebro:
    #   image: yannart/cerebro:0.8.1
    #   ports:
    #     - "9000:9000"
    #   networks:
    #     - bcloud-network
    #   depends_on:
    #     - elasticsearch

networks:
    bcloud-network:
