version: "3"
services:
  bible-matcher:
    build:
      context: ./setup/bible_matcher_node
      dockerfile: Dockerfile
    volumes:
      - ./setup/bible_matcher_node:/var/www/html
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    entrypoint: "sh -c 'yarn && node index.js'"
    expose:
      - 3000

  lilypond:
    build:
      context: ./setup/lilypond
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./data/lilypond:/scoresl
    expose:
      - 8080

  cron:
    build:
      context: ./setup/cron
      dockerfile: Dockerfile
    volumes:
      - ./logs:/var/log

  php-queue:
    build:
      context: ./setup/php-base
      dockerfile: Dockerfile
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - "..:/var/www/html"
