version: "3"
services:
  elasticsearch:
    build:
      context: ./setup/elastic
      dockerfile: Dockerfile
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
    expose:
      - 9200
  # todo: move depends_on and ports to docker-compose.stating.yml
  # kibana:
  #     image: docker.elastic.co/kibana/kibana:7.2.0
  #     ports:
  #         - '9010:5601'
  #     depends_on:
  #         - elasticsearch
  # cerebro:
  #   image: yannart/cerebro:0.8.1
  #   ports:
  #     - "9000:9000"
  #   depends_on:
  #     - elasticsearch

networks:
  bcloud-network:
