version: "3"
services:
  web:
    build:
      context: ./setup/fpm
      dockerfile: Dockerfile
    volumes:
      - "..:/var/www/html"
      # this causes node_modules to be ignored from mount
      - "/var/www/html/node_modules"
      - "/var/www/html/vendor"
    dns:
      - 8.8.8.8
      - 4.4.4.4

  nginx:
    image: "nginx:1.17.3"
    volumes:
      - "..:/var/www/html"
      - "/var/www/html/node_modules"
      - "/var/www/html/vendor"
      - "./config/nginx:/etc/nginx/conf.d"
      - "./logs/nginx:/var/log/nginx"
