version: '2'

services:

  elasticsearch:
    build: .
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  # cerebro:
  #   image: yannart/cerebro:0.8.1
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - elastic
  #   depends_on:
  #     - elasticsearch

networks:

  elastic:
    driver: bridge